---
Name: Phasmophobia
---
bemusedrat\phasmophobia\Ghost:
  extensions:
    - 'TractorCow\Fluent\Extension\FluentExtension'

bemusedrat\phasmophobia\Evidence:
  extensions:
    - 'TractorCow\Fluent\Extension\FluentExtension'